apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-items
  description: Centralizes all item related requests from Checkout IO to the Checkout API.
  annotations:
    github.com/project-slug: vtex-apps/order-items
    vtex.com/o11y-os-index: ""
    vtex.com/janus-acronym: ""
    grafana/dashboard-selector: ""
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: Q547DQ7L
  tags:
    - typescript
    - react
spec:
  type: library
  lifecycle: experimental
  owner: te-0001
  system: checkout
  dependsOn:
    - component:checkout-graphql
  subcomponentOf: checkout-cart