export const mockOrderForm = Object.freeze({
  items: [
    {
      additionalInfo: {
        brandName: 'Test Brand 0',
      },
      availability: 'available',
      id: '1',
      detailUrl: '/work-shirt/p',
      imageUrl:
        'http://storecomponents.vteximg.com.br/arquivos/ids/155476-55-55/Frame-4.jpg?v=636793808441900000',
      listPrice: 2800000,
      measurementUnit: 'un',
      name: 'قميص العمل الأعلى',
      price: 2400000,
      productId: '1',
      quantity: 3,
      sellingPrice: 2400000,
      skuName: 'Test SKU 0',
      skuSpecifications: [],
      uniqueId: 'SomeUniqueId0',
      seller: '0',
      attachmentOfferings: [],
      attachments: [],
      bundleItems: [],
      offerings: [],
      priceTags: [],
      isGift: false,
    },
    {
      additionalInfo: {
        brandName: 'Test Brand 1',
      },
      availability: 'available',
      id: '30',
      detailUrl: '/long-sleeve-shirt/p',
      imageUrl:
        'http://storecomponents.vteximg.com.br/arquivos/ids/155487-55-55/Frame-7.jpg?v=636793837686400000',
      listPrice: 945000,
      measurementUnit: 'un',
      name: '上品なサングラス',
      price: 945000,
      productId: '2000005',
      quantity: 1,
      sellingPrice: 945000,
      skuName: 'Test SKU 1',
      skuSpecifications: [],
      uniqueId: 'SomeUniqueId1',
      seller: '0',
      attachmentOfferings: [],
      attachments: [],
      bundleItems: [],
      offerings: [],
      priceTags: [],
      isGift: false,
    },
    {
      additionalInfo: {
        brandName: 'Test Brand 2',
      },
      availability: 'withoutStock',
      id: '2000535',
      detailUrl: '/classy--sunglasses/p',
      imageUrl:
        'http://storecomponents.vteximg.com.br/arquivos/ids/155469-55-55/Frame-8.jpg?v=636793757498800000',
      listPrice: 400000,
      measurementUnit: 'un',
      name: 'กางเกงขาสั้น',
      price: 360000,
      productId: '13',
      quantity: 4,
      sellingPrice: 360000,
      skuName: 'Test SKU 2',
      skuSpecifications: [],
      uniqueId: 'SomeUniqueId2',
      seller: '0',
      attachmentOfferings: [],
      attachments: [],
      bundleItems: [],
      offerings: [],
      priceTags: [],
      isGift: false,
    },
  ],
  marketingData: null,
  totalizers: [
    {
      id: 'Items',
      name: 'Items Total',
      value: 9585000,
    },
  ],
  value: 9585000,
})

export const mockCatalogItem: CatalogItem = {
  id: '140133',
  productId: '256019',
  availability: 'AVAILABLE',
  quantity: 1,
  uniqueId: '',
  detailUrl: '/macacao-pantalona-xo-uruca-preto-266569-0013-256019/p',
  name: 'Macacao Pantalona Xo Uruca',
  additionalInfo: {
    brandName: 'Farm',
  },
  seller: 'lojafarm',
  skuName: 'Preto - PP',
  price: 69800,
  listPrice: 69800,
  sellingPrice: 69800,
  measurementUnit: 'un',
  skuSpecifications: [],
  imageUrl:
    'https://lojafarm.vtexassets.com/arquivos/ids/1930594-55-55/266569_0013_1-MACACAO-PANTALONA-XO-URUCA.jpg',
}

export const mockCatalogItems: CatalogItem[] = [
  {
    id: '2000536',
    availability: 'AVAILABLE',
    additionalInfo: {
      brandName: 'Samsung',
    },
    productId: '2000004',
    quantity: 1,
    detailUrl: '/st-tropez-shorts/p',
    name: 'St Tropez Top Shorts',
    seller: '1',
    skuName: 'Navy Blue',
    price: 303000,
    listPrice: 303000,
    sellingPrice: 303000,
    measurementUnit: 'un',
    skuSpecifications: [],
    imageUrl:
      'https://storecomponents.vtexassets.com/arquivos/ids/155488-500-auto?width=500&height=auto&aspect=true',
    options: [],
  },
  {
    id: '2000543',
    additionalInfo: {
      brandName: 'Make B.',
    },
    availability: 'AVAILABLE',
    productId: '2000008',
    quantity: 1,
    detailUrl: '/blouse-with-knot/p',
    name: 'Blouse with Knot',
    seller: '1',
    skuName: 'Grey',
    price: 12800,
    listPrice: 12800,
    sellingPrice: 12800,
    measurementUnit: 'un',
    skuSpecifications: [],
    imageUrl:
      'https://storecomponents.vtexassets.com/arquivos/ids/155497-500-auto?width=500&height=auto&aspect=true',
    options: [],
  },
]

export const mockCatalogItems2: CatalogItem[] = [
  {
    id: '310124169',
    availability: 'AVAILABLE',
    additionalInfo: {
      brandName: 'Samsung',
    },
    productId: '2000004',
    quantity: 1,
    uniqueId: '',
    detailUrl: '/st-tropez-shorts/p',
    name: 'St Tropez Top Shorts',
    seller: '1',
    skuName: 'Green',
    price: 8009.999999999999,
    listPrice: 8009.999999999999,
    sellingPrice: 8009.999999999999,
    measurementUnit: 'un',
    skuSpecifications: [],
    imageUrl:
      'https://storecomponents.vtexassets.com/arquivos/ids/155607/St-Tropez-Top-Shorts---verde.jpg?v=637098724114770000',
    options: [],
  },
  {
    id: '2000546',
    additionalInfo: {
      brandName: 'Make B.',
    },
    availability: 'AVAILABLE',
    productId: '2000008',
    quantity: 1,
    uniqueId: '',
    detailUrl: '/blouse-with-knot/p',
    name: 'Blouse with Knot',
    seller: '1',
    skuName: 'Grey',
    price: 12800,
    listPrice: 12800,
    sellingPrice: 12800,
    measurementUnit: 'un',
    skuSpecifications: [],
    imageUrl:
      'https://storecomponents.vtexassets.com/arquivos/ids/155497-500-auto?width=500&height=auto&aspect=true',
    options: [],
  },
]

export const mockItemSeller1 = {
  id: '2000536',
  availability: 'AVAILABLE',
  additionalInfo: {
    brandName: 'Samsung',
  },
  productId: '2000004',
  quantity: 1,
  uniqueId: '',
  detailUrl: '/st-tropez-shorts/p',
  name: 'St Tropez Top Shorts',
  seller: '1',
  skuName: 'Navy Blue',
  price: 303000,
  listPrice: 303000,
  sellingPrice: 303000,
  measurementUnit: 'un',
  skuSpecifications: [],
  imageUrl:
    'https://storecomponents.vtexassets.com/arquivos/ids/155488-500-auto?width=500&height=auto&aspect=true',
  options: [],
  isGift: false,
}

export const mockItemSeller2 = {
  ...mockItemSeller1,
  id: `${mockItemSeller1.id}2`,
  seller: '2',
}
